# Basic
name:               "Anaanu Webstudio"

# URL
url:                "http://localhost:4000" # use this url when you develop
timezone:           Africa/Accra
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Studio"
    url:            "/"
  - name:           "Blog"
    url:            "/archive"
  # - name:           "About"
  #   url:            "/tags"
  # - name:           "Contact"
  #   url:            "#"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
