# Basic
name:               "Anaanu Webstudio"
title:              "Anaanu Webstudio // Build Effective Websites"
# URL to a site-wide logo
logo:              "/assets/images/anaanu.site.png"
author:             "thesowah"

# URL
url:                "http://localhost:4000"
timezone:           Africa/Accra
permalink:          /blog/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Studio"
    url:            "/"
  - name:           "Blog"
    url:            "/blog/"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
      image:        "/assets/images/anaanu.site.png"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-sitemap

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

# Collections
collections:
  portfolio:
    output: true
    permalink: /blog/:path/

# Server Config options
livereload: true     # You no longer need to include --livereload

author:
  name:             "Adjetey Sowah"
  facebook:         "anaanuwebstudio"
  twitter:          "anaanuwebstudio"
  instagram:        "anaanuwebstudio"
  linkedin:         "anaanu-webstudio"
  disqus:           "anaanuwebstudio"
  email:            "info@anaanu.site"

