# Basic
name:               "Anaanu Webstudio"
tagline: "Everything websites"
description: "A creative studio that helps people build effective websites."

# URL
url:                "http://localhost:4000"
timezone:           Africa/Accra
permalink:          /blog/:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Studio"
    url:            "/"
  - name:           "Blog"
    url:            "/blog/"
  - name:           "Info"
    url:            "#"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

# Collections
collections:
  portfolio:
    output: true
    permalink: /blog/:path/

# Disqus
disqus:
  id:               "anaanuwebstudio"

owner:
  mailto:           "mailto:info@anaanu.site?subject=Let's work together"
